### PR TITLE
Fix  'Unknown' country bug Closes #1102

### LINKED ISSUE #1102: Erroneous display of IP:s that can't be geolocated
IP:s that can't be geolocated (i.e. "null") displays as  [object Object]
Skärmavbild 2022-04-12 kl  19 02 58
]

### PR DESCRIPTION
**Pull request by briancao**
Fix null country showing as [Object object] instead of 'Unknown'

### CODE REVIEW

File: components/common/FilterLink.js [hunk 1]
```diff
@@ -21,7 +21,9 @@ export default function FilterLink({ id, value, label, externalUrl }) {
             [styles.active]: active && selected,
           })}
         >
-          {safeDecodeURI(label || value)}
+          {(label && typeof label === 'string') ?? value
+            ? safeDecodeURI(label || value)
+            : label || value}
```
Comment (mikecao) [inline components/common/FilterLink.js:26]: Too confusing

**Review by mikecao — CHANGES_REQUESTED** [review]

File: components/common/FilterLink.js (hunk 1 above)
Comment (briancao) [reply components/common/FilterLink.js]: removed safeDecodrURI alltogether.

**Comment by pqvst** [comment]
This PR broke URL rendering for non-English languages, such as Arabic, Japanese, Chinese, Korean, etc. #1171
